from src.Exceptions.ExceptionBase import ExceptionBase

class DuplicateUserError(ExceptionBase):
    pass
